### ISSUE TITLE
Fix the random test flakes when test server is not ready

### ISSUE THREAD

**Issue by tbetbetbe** [google/dorusu-js#21]
Sometimes the test 'headers special: timeout headers should succeed in sending a good grpc-timeout value' fails with the following error.  Let's re-write that test to stop this from happening.

  1) Base RPC Client insecure: headers special: timeout headers should succeed in sending a good grpc-timeout value:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:41009
      at Object.exports._errnoException (util.js:856:11)
      at exports._exceptionWithHostPort (util.js:879:20)
      at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)

**Comment by tbetbetbe** [comment]
N.B. This test failure occurs sporadically for any test where a server is started up.

**Comment by tbetbetbe** [comment]
Some delays introduced in #25 appear to have resolved this.
Closing, but will re-open if this starts happening regularly again
